### ISSUE TITLE
where is the  pmrp in code evalution?

### ISSUE THREAD

**Issue by ahustr** [VL-Group/2022-NeurIPS-DAA#1]
Thank you for your excellent work, i want to know where is the  pmrp in code evalution?

**Comment by leolee99** [comment]
Hi, thanks for your interest in our work. I have uploaded the code of pmrp evaluation.

**Comment by ahustr** [comment]
thank you very much! However, I find that the code '%s_caption_ids.txt' in the pmrp_data.py, what is the file '%s_caption_ids.txt'?

**Comment by leolee99** [comment]
Sorry, I forgot it. Now I have re-uploaded some files. You can find the file '%s_caption_ids.txt' in "pmrp_com/".

**Comment by ahustr** [comment]
The author is a gentleman！

**Comment by leolee99** [comment]
Thanks ~
